# .kodiak.toml
version = 1

[merge]
automerge_label = "ready to land"
require_automerge_label = true
method = "squash"
delete_branch_on_merge = true
optimistic_updates = true
prioritize_ready_to_merge = false
notify_on_conflict = false

[merge.message]
title = "pull_request_title"
body = "pull_request_body"
include_coauthors = true
include_pr_number = true
include_pull_request_url = true
body_type = "markdown"
strip_html_comments = true

[approve]
approve.auto_approve_labels = ["approve"]