name: Integration

on: push

jobs:
  static:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: ['18.15.0']
        os: [ubuntu-latest, windows-latest, macOS-latest]
        pnpm: [8.11.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: ${{ matrix.pnpm }}
          run_install: false

      - name: Install Node.js (${{ matrix.node }})
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Format
        run: pnpm run format

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build
