name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up node environment
        uses: actions/setup-node@v2-beta
        with:
          node-version: 16.14.0

      - name: Cache node modules
        id: node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - if: steps.node-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
