name: Release

on:
  push:
    paths:
      - '.changeset/**'
      - 'packages/**'

    branches:
      - master

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 16.14.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.0

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Setup CI Git User
        run: |
          git config --global user.email "helloyonycalsin@gmail.com"
          git config --global user.name "Yony Calsin"

      - name: Publish packages
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn run release
          version: yarn run version
          commit: 'chore(release): version packages'
          setupGitUser: false
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
